# Generated by Django 5.0.4 on 2024-04-26 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Baby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=255)),
                ('lname', models.CharField(max_length=255)),
                ('age', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=255)),
                ('broughtby', models.CharField(max_length=200)),
                ('parent_name', models.CharField(max_length=200)),
                ('periodstay', models.CharField(max_length=20)),
                ('message_left', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Sitter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=255)),
                ('lname', models.CharField(max_length=255)),
                ('age', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=255)),
                ('DOB', models.CharField(max_length=200)),
                ('NxtoK', models.CharField(max_length=150)),
                ('NIN', models.CharField(blank=True, max_length=50, null=True)),
                ('fees', models.FloatField()),
                ('recommender', models.CharField(max_length=200)),
                ('educationlevel', models.CharField(max_length=20)),
                ('sitternumber', models.CharField(max_length=50)),
                ('message_left', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_number', models.IntegerField(blank=True, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('payee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.baby')),
                ('payment_sitter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.sitter')),
            ],
        ),
    ]
