# Generated by Django 5.0.4 on 2024-05-09 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_categorystay_item_remove_baby_periodstay_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitter',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
