# Generated by Django 5.0.4 on 2024-04-26 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_categorystay_pay_payment_cat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitter',
            name='fees',
        ),
        migrations.RemoveField(
            model_name='sitter',
            name='message_left',
        ),
        migrations.AddField(
            model_name='sitter',
            name='contact',
            field=models.CharField(default=1, max_length=20),
        ),
    ]
