# Generated by Django 5.0.4 on 2024-04-27 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_remove_sitter_fees_remove_sitter_message_left_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baby',
            name='babynumber',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='baby',
            name='fees',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='baby',
            name='timein',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='baby',
            name='timeout',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='baby',
            name='broughtby',
            field=models.CharField(max_length=100),
        ),
    ]
