# Generated by Django 5.0.4 on 2024-04-29 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_baby_babynumber_baby_fees_baby_timein_baby_timeout_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dolls', models.CharField(max_length=50)),
                ('toys', models.CharField(max_length=50)),
                ('milk', models.CharField(max_length=50)),
                ('daipers', models.CharField(max_length=50)),
                ('babyfood', models.CharField(max_length=50)),
                ('fruits', models.CharField(max_length=50)),
                ('date_recieved', models.DateField()),
            ],
        ),
    ]
