# Generated by Django 5.0.4 on 2024-05-10 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_pay_baby_alter_pay_date_alter_pay_payee'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitter',
            name='babe',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='application.baby'),
        ),
    ]
