# Generated by Django 5.0.4 on 2024-04-30 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_baby_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baby',
            name='timein',
            field=models.DateTimeField(),
        ),
    ]
