# Generated by Django 5.0.4 on 2024-05-10 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_remove_sitter_babe'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitter',
            name='babe',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='application.baby'),
        ),
    ]
