# Generated by Django 5.0.4 on 2024-05-12 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_sitter_babe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pay',
            name='payee',
        ),
        migrations.RemoveField(
            model_name='sitter',
            name='babe',
        ),
        migrations.AlterField(
            model_name='pay',
            name='pay_status',
            field=models.BooleanField(default=0),
        ),
    ]
