# Generated by Django 5.0.4 on 2024-05-03 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_alter_baby_timein'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='babyfood',
            new_name='current_stock',
        ),
        migrations.RemoveField(
            model_name='item',
            name='daipers',
        ),
        migrations.RemoveField(
            model_name='item',
            name='dolls',
        ),
        migrations.RemoveField(
            model_name='item',
            name='fruits',
        ),
        migrations.RemoveField(
            model_name='item',
            name='milk',
        ),
        migrations.RemoveField(
            model_name='item',
            name='toys',
        ),
        migrations.AddField(
            model_name='item',
            name='item_name',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='quantity',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
    ]
