# Generated by Django 5.0.4 on 2024-05-03 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_rename_babyfood_item_current_stock_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='date_recieved',
        ),
    ]
