# Generated by Django 5.0.4 on 2024-05-12 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_pay_payee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pay',
            name='payee',
        ),
    ]
