# Generated by Django 5.0.4 on 2024-05-05 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_remove_item_date_recieved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pay',
            name='payment_sitter',
        ),
        migrations.AlterField(
            model_name='baby',
            name='image',
            field=models.ImageField(max_length=255, upload_to=''),
        ),
    ]
