# Generated by Django 5.0.4 on 2024-05-13 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_remove_pay_payee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitter',
            name='status',
            field=models.BooleanField(default=0),
        ),
    ]
