# Generated by Django 5.0.4 on 2024-05-05 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_remove_pay_payment_sitter_alter_baby_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baby',
            old_name='category',
            new_name='stay_duration',
        ),
        migrations.RemoveField(
            model_name='baby',
            name='periodstay',
        ),
        migrations.AlterField(
            model_name='baby',
            name='broughtby',
            field=models.CharField(max_length=200),
        ),
    ]
