# Generated by Django 5.0.4 on 2024-05-14 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_alter_sitter_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doll_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('item_description', models.CharField(max_length=100)),
                ('item_quantity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Doll_transction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('buy', 'buy'), ('sell', 'sell')], max_length=100)),
                ('transaction_quantity', models.IntegerField(default=0)),
                ('transaction_date', models.DateField(auto_now_add=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('doll_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.doll_item')),
            ],
        ),
    ]
