# Generated by Django 5.0.4 on 2024-05-05 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_rename_category_baby_stay_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baby',
            name='timein',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
