# Generated by Django 5.0.4 on 2024-05-15 05:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0012_doll_item_doll_transction'),
    ]

    operations = [
        migrations.AddField(
            model_name='doll_item',
            name='date_added',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
