# Generated by Django 5.0.4 on 2024-05-15 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0013_doll_item_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baby',
            name='stay_duration',
            field=models.CharField(blank=True, choices=[('fullday', 'fullday'), ('halfday', 'halfday')], max_length=50, null=True),
        ),
    ]
