# Generated by Django 5.0.4 on 2024-05-15 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0018_remove_pay_pay_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pay',
            name='stay_duration',
            field=models.IntegerField(default=1),
        ),
    ]
