# Generated by Django 5.0.4 on 2024-05-15 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0020_alter_pay_stay_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baby',
            name='stay_duration',
        ),
        migrations.AlterField(
            model_name='pay',
            name='stay_duration',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
