# Generated by Django 5.0.4 on 2024-05-15 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0024_pay_stay_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pay',
            name='stay_duration',
        ),
        migrations.AddField(
            model_name='baby',
            name='stay_duration',
            field=models.CharField(blank=True, choices=[('fullday', 'fullday'), ('halfday', 'halfday')], max_length=50, null=True),
        ),
    ]
