# Generated by Django 5.0.4 on 2024-05-15 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0025_remove_pay_stay_duration_baby_stay_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitter',
            name='sit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sitters', to='application.baby'),
        ),
    ]
