# Generated by Django 5.0.4 on 2024-05-16 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0026_sitter_sit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitter',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
