# Generated by Django 5.0.4 on 2024-05-16 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0030_alter_sitter_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pay',
            name='stay_duration',
            field=models.CharField(blank=True, default='Fullday', max_length=15),
        ),
    ]
