# Generated by Django 5.0.4 on 2024-05-18 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0031_pay_stay_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='baby',
            name='sittr',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='application.sitter'),
        ),
    ]
